name: Reusable deploy workflow

on:
  workflow_call:
    inputs:
      deploy_command:
        required: true
        type: string
      env:
        required: true
        type: string
    secrets:
      DBX_URL:
        required: true
      DBX_TOKEN:
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          miniconda-version: 'py38_4.8.3'

      - name: cache venv
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: |
            .venv
            ~/.poetry/env
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: setup secrets
        env:
          ENV: ${{ inputs.env }}
          DBX_URL: ${{ secrets.DBX_URL }}
          DBX_TOKEN: ${{ secrets.DBX_TOKEN }}
        run: |
          cp .env.dist .env
          sed -i "s,DBX_TOKEN=,DBX_TOKEN=$DBX_TOKEN,g" .env
          sed -i "s,\[Your workspace address\],$DBX_URL,g" src/$(ls src)/_config/config_$ENV.yaml

      - name: setup
        run: |
          export SHELL=$SHELL # for python to be able to access the bash version
          chmod +x env-init.sh
          ./env-init.sh -y --verbose

      - name: deploy
        run: |
          eval "$(conda shell.bash hook)"
          conda activate $PWD/.venv
          source ~/.poetry/env
          poetry install --no-root
          ${{ inputs.deploy_command }}
