name: Prod pipeline
on:
  release:
    types: [published]

jobs:
  build:
    uses: daipe-ai/skeleton-databricks/.github/workflows/build.yml@master

  deploy:
    needs: build
    uses: daipe-ai/skeleton-databricks/.github/workflows/run_command.yml@master
    with:
      command: daipe dbx:repo:update --env=test --repo-url=${{ github.server_url }}/${{ github.repository }}.git --tag=${{ github.ref }} --repo-name=master
      env: prod
    secrets:
      DBX_URL: ${{ secrets.DBX_URL }}
      DBX_TOKEN: ${{ secrets.DBX_TOKEN }}
